name: protein_ai

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - pip
  - pip:
      - transformers
      - accelerate
      - biopython