name: protein_ai

channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn             
  - umap-learn          
  - pymol-open-source   
  - requests            
  - ipykernel           
  - pip
  - pip:
      - transformers
      - accelerate
      - biopython